"""Added Color Identity

Revision ID: 52460d58bb58
Revises: 81ae7a052ae8
Create Date: 2024-10-02 12:00:43.533480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52460d58bb58'
down_revision = '81ae7a052ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overlay', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player1_commander1_color_identity', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('player1_commander2_color_identity', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('player2_commander1_color_identity', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('player2_commander2_color_identity', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('player3_commander1_color_identity', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('player3_commander2_color_identity', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('player4_commander1_color_identity', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('player4_commander2_color_identity', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overlay', schema=None) as batch_op:
        batch_op.drop_column('player4_commander2_color_identity')
        batch_op.drop_column('player4_commander1_color_identity')
        batch_op.drop_column('player3_commander2_color_identity')
        batch_op.drop_column('player3_commander1_color_identity')
        batch_op.drop_column('player2_commander2_color_identity')
        batch_op.drop_column('player2_commander1_color_identity')
        batch_op.drop_column('player1_commander2_color_identity')
        batch_op.drop_column('player1_commander1_color_identity')

    # ### end Alembic commands ###
