"""Initial DB

Revision ID: 81ae7a052ae8
Revises: 
Create Date: 2024-10-01 17:36:34.423381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ae7a052ae8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overlay',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('player1_commander1', sa.String(), nullable=True),
    sa.Column('player1_commander2', sa.String(), nullable=True),
    sa.Column('player2_commander1', sa.String(), nullable=True),
    sa.Column('player2_commander2', sa.String(), nullable=True),
    sa.Column('player3_commander1', sa.String(), nullable=True),
    sa.Column('player3_commander2', sa.String(), nullable=True),
    sa.Column('player4_commander1', sa.String(), nullable=True),
    sa.Column('player4_commander2', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('overlay')
    op.drop_table('user')
    # ### end Alembic commands ###
